"""Quantize a checkpoint to int8 and write the files the device needs.

    python train/export.py

Writes:
    firmware/data/model.bin        raw model (host build loads this)
    firmware/src/model_data.h      same bytes as a C array (flashed with the firmware)

Format (little endian, every block padded to 4 bytes):
    u32 magic "TAI1", version, vocab, ctx, dim, layers, heads, hidden, n_known
    tok, pos                         int8[rows*cols] + f32[rows] scales
    per layer: n1 f32[dim], wq wk wv wo, n2 f32[dim], w1 w2
    norm f32[dim]
    u32 len, known questions as NUL-separated normalized strings
"""

import argparse
import struct

import numpy as np
import torch

from common import load_facts, normalize


def pad4(b):
    return b + b"\0" * (-len(b) % 4)


def qmat(w):
    """Symmetric per-row int8. Returns bytes and the max abs round-trip error."""
    w = w.detach().float().numpy()
    scale = np.abs(w).max(axis=1) / 127.0
    scale[scale == 0] = 1.0
    q = np.clip(np.round(w / scale[:, None]), -127, 127).astype(np.int8)
    err = np.abs(q * scale[:, None] - w).max()
    return pad4(q.tobytes()) + scale.astype("<f4").tobytes(), err


def f32(t):
    return t.detach().float().numpy().astype("<f4").tobytes()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ckpt", default="train/ckpt.pt")
    ap.add_argument("--data", default="data/facts.tsv")
    ap.add_argument("--bin", default="firmware/data/model.bin")
    ap.add_argument("--header", default="firmware/src/model_data.h")
    args = ap.parse_args()

    ck = torch.load(args.ckpt, map_location="cpu")
    c, sd = ck["cfg"], ck["model"]
    known = sorted({normalize(q) for qs, _ in load_facts(args.data) for q in qs})

    out = [struct.pack("<9I", 0x31494154, 1, c["vocab"], c["ctx"], c["dim"], c["layers"],
                       c["heads"], c["hidden"], len(known))]
    worst = 0.0

    def add_q(name):
        nonlocal worst
        b, e = qmat(sd[name])
        worst = max(worst, e)
        out.append(b)

    add_q("tok.weight")
    add_q("pos.weight")
    for l in range(c["layers"]):
        p = f"blocks.{l}."
        out.append(f32(sd[p + "n1.w"]))
        for n in ("wq", "wk", "wv", "wo"):
            add_q(p + n + ".weight")
        out.append(f32(sd[p + "n2.w"]))
        add_q(p + "w1.weight")
        add_q(p + "w2.weight")
    out.append(f32(sd["norm.w"]))
    blob = "\0".join(known).encode() + b"\0"
    out.append(struct.pack("<I", len(blob)) + pad4(blob))
    data = b"".join(out)

    with open(args.bin, "wb") as f:
        f.write(data)
    with open(args.header, "w") as f:
        f.write("// Generated by train/export.py. Do not edit.\n#pragma once\n#include <stdint.h>\n\n")
        f.write(f"static const unsigned int model_data_len = {len(data)};\n")
        f.write("static const uint8_t model_data[] __attribute__((aligned(4))) = {\n")
        for i in range(0, len(data), 32):
            f.write(",".join(str(x) for x in data[i:i + 32]) + ",\n")
        f.write("};\n")
    n_params = sum(v.numel() for v in sd.values())
    print(f"{n_params:,} params -> {len(data):,} bytes, {len(known)} known questions, "
          f"max quantization error {worst:.4f}")


if __name__ == "__main__":
    main()
