# PlatformIO pre-build script: embeds the model file in flash as-is.
#
# Each environment names its model with `custom_model` in platformio.ini. This
# writes a one-line assembler file that .incbin's it into .rodata, so a 10 MB
# model costs no compile time and no giant C header. src/model_data.h declares
# the symbols.
import os

Import("env")  # noqa: F821  (provided by PlatformIO)

model = os.path.join(env.subst("$PROJECT_DIR"), env.GetProjectOption("custom_model", "data/model.bin"))  # noqa: F821
if not os.path.exists(model):
    raise SystemExit(f"embed_model.py: {model} not found (run train/export.py)")
st = os.stat(model)
src = os.path.join(env.subst("$BUILD_DIR"), "model_src")  # noqa: F821
os.makedirs(src, exist_ok=True)
asm = os.path.join(src, "model_data.S")
# The size and mtime are in the text so a new model file forces a rebuild.
text = f"""/* Generated by embed_model.py from {os.path.basename(model)}, {st.st_size} bytes, mtime {int(st.st_mtime)}. */
    .section .rodata.model_data, "a"
    .balign 16
    .global model_data
model_data:
    .incbin "{model}"
    .global model_data_end
model_data_end:
"""
if not os.path.exists(asm) or open(asm).read() != text:
    with open(asm, "w") as f:
        f.write(text)
env.BuildSources(os.path.join("$BUILD_DIR", "model_obj"), src)  # noqa: F821
